"""empty message

Revision ID: cc568ccce827
Revises: fecc722df8f9
Create Date: 2023-11-17 20:20:16.835610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc568ccce827'
down_revision: Union[str, None] = 'fecc722df8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('coefficients', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'coefficients')
    # ### end Alembic commands ###
